# Generated by Django 5.1.15 on 2026-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_study_goal',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_goal',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_grade',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
