# Generated by Django 5.1.15 on 2026-08-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_daily_study_goal_profile_main_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coaching_style',
            field=models.CharField(blank=True, default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_style',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_study_time',
            field=models.CharField(blank=True, default='evening', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_length',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
