# Generated by Django 5.1.1 on 2026-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_coaching_style_profile_learning_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
