# Generated by Django 5.1.1 on 2026-06-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_studied', models.PositiveIntegerField(default=0)),
                ('focus_score', models.PositiveIntegerField(default=70)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('breaks_taken', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(choices=[('low', 'Low'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='good', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
