# Generated by Django 5.1.15 on 2026-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_focussession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focussession',
            name='mood',
            field=models.CharField(blank=True, choices=[('terrible', 'Terrible'), ('bad', 'Bad'), ('difficult', 'Difficult'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great'), ('excellent', 'Excellent')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='productivitylog',
            name='mood',
            field=models.CharField(choices=[('low', 'Low'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great'), ('excellent', 'Excellent')], default='good', max_length=10),
        ),
    ]
