# Generated by Django 5.1.15 on 2026-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiprojectusage_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='ad_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
