# Generated by Django 5.1.15 on 2026-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_subject_subject_code_subject_target_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
